// Copyright 2015 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ////////////////////////////////////////////////////////////////////
// This binary implements the ability to load a docker image index, calculate its image manifest sha256 hash and output a digest file.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"os"

	"github.com/bazelbuild/rules_docker/container/go/pkg/utils"
	v1 "github.com/google/go-containerregistry/pkg/v1"

	"github.com/bazelbuild/rules_docker/container/go/pkg/compat"
	"github.com/bazelbuild/rules_docker/container/go/pkg/oci"
)

type applicationArgs struct {
	Format         string
	OutputFilePath string
	Images         []imageArgs
}

type imageArgs struct {
	Platform struct {
		Os      string
		Arch    string
		Variant string
	}
	Config   string
	Layers   []string
	Tarball  string
	Manifest string
}

func parseArgs(argv []string) (*applicationArgs, error) {
	var args applicationArgs

	appName := argv[0]

	fl := flag.NewFlagSet(appName, flag.ContinueOnError)
	fl.StringVar(
		&args.OutputFilePath, "dst", "",
		"The destination location of the digest file to write to.",
	)
	fl.StringVar(
		&args.Format, "format", "",
		"The format of the uploaded image (Docker or OCI).",
	)

	if err := fl.Parse(argv[1:]); err != nil {
		return nil, err
	}

	if args.OutputFilePath == "" {
		return nil, errors.New("required options -dst was not specified")
	}

	if args.Format == "" {
		return nil, errors.New("required options -format was not specified")
	}

	for fl.NArg() > 0 {
		var imageArgs imageArgs

		argv := fl.Args()

		fl = flag.NewFlagSet(appName, flag.ContinueOnError)
		fl.StringVar(
			&imageArgs.Platform.Os, "os", "",
			"OS of the Docker image.",
		)
		fl.StringVar(
			&imageArgs.Platform.Arch, "arch", "",
			"Architecture of the Docker image.",
		)
		fl.StringVar(
			&imageArgs.Platform.Variant, "variant", "",
			"Architecture variant of the Docker image.",
		)

		fl.StringVar(
			&imageArgs.Config, "config", "",
			"Path to the image config.json. Required if --tarball was not specified.",
		)
		fl.Var(
			(*utils.ArrayStringFlags)(&imageArgs.Layers), "layer",
			"One or more layers with the following comma separated values (Compressed layer tarball, Uncompressed layer tarball, digest file, diff ID file)."+
				"e.g., --layer layer.tar.gz,layer.tar,<file with digest>,<file with diffID>.",
		)
		fl.StringVar(
			&imageArgs.Tarball, "tarball", "",
			"Path to the image tarball as generated by docker save. Required if --config was not specified.",
		)
		fl.StringVar(
			&imageArgs.Manifest, "manifest", "",
			"Path to the manifest of the base image. This should be the very first image in the chain of images and is only really required for windows images with a base image that has foreign layers.",
		)

		if err := fl.Parse(argv); err != nil {
			return nil, err
		}

		if imageArgs.Tarball == "" && imageArgs.Config == "" {
			return nil, errors.New("neither --tarball nor --config was specified")
		}

		args.Images = append(args.Images, imageArgs)
	}

	return &args, nil
}

func main() {
	args, err := parseArgs(os.Args)
	if err != nil {
		if err == flag.ErrHelp {
			os.Exit(0)
		}

		_, _ = fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(2)
	}

	if err := run(args); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run(args *applicationArgs) error {
	var content bytes.Buffer

	if len(args.Images) == 0 {
		log.Printf("No provided images.\n")
		return nil
	}

	ii, err := readImageIndex(args)
	if err != nil {
		return err
	}

	digest, err := ii.Digest()
	if err != nil {
		return fmt.Errorf("can't get digest of image index: %v", err)
	}

	_, _ = content.WriteString(fmt.Sprintf("%s\n", digest))

	im, err := ii.IndexManifest()
	if err != nil {
		return fmt.Errorf("can't get index manifest: %v", err)
	}

	for _, manifest := range im.Manifests {
		platform := manifest.Platform
		if platform == nil {
			platform = &v1.Platform{
				Architecture: "amd64",
				OS:           "linux",
			}
		}

		var os string
		if platform.OS != "" {
			os = platform.OS
		} else {
			os = "linux"
		}

		var arch string
		if platform.Architecture != "" {
			arch = platform.Architecture
		} else {
			arch = "amd64"
		}

		platformIdent := os + "/" + arch
		if platform.Variant != "" {
			platformIdent += "/" + platform.Variant
		}

		_, _ = content.WriteString(fmt.Sprintf(
			"%s\t%s\n", platformIdent, manifest.Digest,
		))
	}

	if err := ioutil.WriteFile(args.OutputFilePath, content.Bytes(), os.ModePerm); err != nil {
		return fmt.Errorf("error outputting digest file to %s: %v", args.OutputFilePath, err)
	}

	return nil
}

func readImageIndex(args *applicationArgs) (v1.ImageIndex, error) {
	platforms := make([]v1.Platform, len(args.Images))
	images := make([]v1.Image, len(args.Images))

	for idx, imgArgs := range args.Images {
		parts, err := compat.ImagePartsFromArgs(
			imgArgs.Config, imgArgs.Manifest, imgArgs.Tarball, imgArgs.Layers,
		)

		if err != nil {
			return nil, err
		}

		img, err := compat.ReadImage(parts)
		if err != nil {
			return nil, err
		}

		platforms[idx] = v1.Platform{
			OS:           imgArgs.Platform.Os,
			Architecture: imgArgs.Platform.Arch,
			Variant:      imgArgs.Platform.Variant,
		}
		images[idx] = img
	}

	ii, err := compat.NewImageIndex(platforms, images)
	if err != nil {
		return nil, err
	}

	if args.Format == "OCI" {
		ii, err = oci.AsOCIImageIndex(ii)
		if err != nil {
			return nil, fmt.Errorf("failed to convert image index to OCI format: %v", err)
		}
	}

	return ii, nil
}
